### ISSUE TITLE
Jacksum-1.7.0-windows-explorer-integration-1.4.0 does not find Oracle JDK 17 (installed) or OpenJDK (extracted from .zip)

### ISSUE THREAD

**Issue by BlindDuck** [jonelo/jacksum-fbi-windows#1]
On W10

Java from:
-Oracle (exe)
-OpenJDK (zip)

was intalled but non was recognised by the installer, see screen shoots.
![2021-12-12 11_41_21-C__Program Files_Java](https://user-images.githubusercontent.com/24966241/146018001-b1a47fbd-9e7f-406a-a157-eddae0170621.png)
![2021-12-12 11_25_14-Java(TM) SE Development Kit 17 0 1 (64-bit) - Destination Folder](https://user-images.githubusercontent.com/24966241/146018003-e9c0c3e5-ac94-482e-9a06-94b93764bddc.png)
![2021-12-09 08_51_32-Jacksum Windows Explorer Integration 1 4 0](https://user-images.githubusercontent.com/24966241/146018005-2f8cca1e-6ea3-4692-bd6d-083d6602a95b.png)

A hint in the requirements where and/or what the installer expects would be apreciated.

**Comment by jonelo** [comment]
Thanks BlindDuck for reporting this. I can reproduce the issue. I moved the report to this repo, because it has to do with the installer and not with Jacksum itself.

The root cause is that Oracle JDK 17 use different registry keys for registering the Oracle JDK, and the installer (which was build in 2016 when Oracle JDK 8 was up to date) cannot find it, because the installer on Windows was not tested with Oracle JDK 17.

Fortunatley, the installer does not only rely on registry keys. Actually it also reads the value of JAVA_HOME if it is set.
So as a workaround you can do the following:

a) save the "Jacksum Windows Explorer Integration.exe" to your Desktop by drag and drop it from the .zip file

b) open a command prompt by hitting WindowsKey+R, and typing cmd, followed by Enter

c) set the environment variable called JAVA_HOME to the path of your preferred JDK.
Example: `set JAVA_HOME=C:\Program Files\Java\jdk-17.0.1`

d) run the Jacksum Windows Explorer Integration.exe from the the desktop in the current shell (with the environment variable set):
Example: `"%USERPROFILE%\Desktop\Jacksum Windows Explorer Integration.exe"`

and the installer should find the later JDK as specified, and install Jacksum 1.7.0 to the Windows Explorer.
