### ISSUE TITLE
I'm stuck with this and dont know how to delete it

### ISSUE THREAD

**Issue by asmael79** [jonelo/jacksum-fbi-windows#4]
I deleted the program.
Now whenever I press send to on a file I get a screen full of junk
![Capture](https://github.com/user-attachments/assets/0d53ffd8-e9e5-45fd-a287-513e4633c201)

**Comment by jonelo** [comment]
It seems that you are using a very old version of the “Jacksum File Browser Integration”.
Nevertheless, even in the oldest versions there is an uninstaller that can remove everything that the installer has installed.

The easiest way to fix your problem is probably to restart the installer and run the uninstaller, which will do the job for you. Alternatively, you can also select the menu item “Open SendTo folder” and remove all symbolic links from this folder.

After uninstalling, you should take a look at the latest Jacksum/HashGarten package for Windows, available [here](https://github.com/jonelo/jacksum-for-windows). And if you don't like it either, there is always an uninstaller ;-)
